name: 'My Composite Action'
description: 'A composite action that combines multiple steps'
inputs:
  name:
    description: 'Name to greet'
    required: true
    default: 'World'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print greeting
      run: echo "Hello ${{ inputs.name }}!"
      shell: bash

    - name: List files in the repository
      run: ls -la
      shell: bash
